import { arquivoBBDD } from "../Tipos/bbdd.tipos";
import { DatoBBDD } from "../Tipos/datos.base.interfaces";

let creacionTablasBBDD: DatoBBDD = {
  bbdd: `

CREATE TABLE IF NOT EXISTS PRODUCTO (
  ID_PRODUCTO INTEGER PRIMARY KEY AUTOINCREMENT,
  CODIGO_PRODUCTO                  TEXT,
  NOME_PRODUCTO                    TEXT,
  DESCRIPCION_PRODUCTO             TEXT NOT NULL,
  PESO_PRODUCTO                    REAL,
  PRECIO_PRODUCTO                  NUMERIC NOT NULL,
  TIPO_PRODUCTO                    TEXT,
  STOCK_PRODUCTO                   NUMERIC NOT NULL
);

CREATE TABLE IF NOT EXISTS CLIENTE (
  ID_CLIENTE INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME_CLIENTE                     TEXT,
  APELIDO1_CLIENTE                 TEXT,
  EMPRESA_CLIENTE                  TEXT NOT NULL,
  PROFESION_CLIENTE                TEXT,
  ROL_CLIENTE                      TEXT,
  EMAIL_CLIENTE                    TEXT
);

CREATE TABLE IF NOT EXISTS TRABALLADOR (
  ID_USER_TRABALLADOR INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME_USER_TRABALLADOR            TEXT,
  APELIDO1_TRABALLADOR             TEXT,
  APELIDO2_TRABALLADOR             TEXT,
  PWD_TRABALLADOR                  TEXT,
  EMAIL_TRABALLADOR                TEXT,
  ROL_TRABALLADOR                  TEXT
);

CREATE TABLE IF NOT EXISTS FACTURA (
  ID_FACTURA INTEGER PRIMARY KEY AUTOINCREMENT,
  CODIGO_FACTURA                   TEXT,
  NOME_PRODUCTO_FACTURA            TEXT,
  FECHA_FACTURA                    TEXT,
  CODIGO_PRODUCTO_FACTURA          TEXT,
  CANTIDADE_PRODUCTO_FACTURA       INTEGER,
  PRECIO_PRODUCTO_FACTURA          REAL,
  FOREIGN KEY (CODIGO_PRODUCTO_FACTURA) REFERENCES PRODUCTO(CODIGO_PRODUCTO) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS FACTURAS (
  ID_FACTURAS INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_CLIENTE_FACTURAS              INTEGER NOT NULL,
  CODIGO_FACTURA_FACTURAS          TEXT,
  TOTAL                             REAL,
  PAGADA                            INTEGER,
  FOREIGN KEY (CODIGO_FACTURA_FACTURAS) REFERENCES FACTURA(CODIGO_FACTURA) ON UPDATE CASCADE,
  FOREIGN KEY (ID_CLIENTE_FACTURAS) REFERENCES CLIENTE(ID_CLIENTE)
);

`
};

let arquivosBBDD: arquivoBBDD = {
  xeral: "basedatos.db",
  persoal: "proba.israel.db"
};

export {
  creacionTablasBBDD,
  arquivosBBDD
};
